/*
 * Copyright (C) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
//https://media.w3.org/2010/05/sintel/trailer.mp4
//http://mirror.aarnet.edu.au/pub/TED-talks/911Mothers_2010W-480p.mp4  //长视频
export class CommonConstants {
  static readonly VIDEO_HTTPS_LISTS: Array<string> = [
    'https://img.tukuppt.com/video_show/2418175/00/44/50/603eda4ce3c22.mp4',
    'https://vjs.zencdn.net/v/oceans.mp4',
    'http://mirror.aarnet.edu.au/pub/TED-talks/911Mothers_2010W-480p.mp4',
    'https://www.w3schools.com/html/movie.mp4',
    'http://1251017968.vod2.myqcloud.com/3eb04eefvodtransgzp1251017968/8782b1285285890810009576163/v.f30.mp4',
    'https://media.w3.org/2010/05/sintel/trailer.mp4']
}